name: Dependency Updates

on:
  schedule:
    # Run weekly on Mondays at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch: # Allow manual triggering

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        
    - name: Install pip-tools
      run: |
        python -m pip install --upgrade pip
        pip install pip-tools
        
    - name: Update requirements
      run: |
        pip list --outdated --format=json > outdated-packages.json
        
    - name: Check for security vulnerabilities
      run: |
        pip install safety
        safety check --json --output safety-check.json || true
        
    - name: Create issue for outdated packages
      uses: actions/github-script@v6
      if: always()
      with:
        script: |
          const fs = require('fs');
          
          try {
            const outdated = JSON.parse(fs.readFileSync('outdated-packages.json', 'utf8'));
            
            if (outdated.length > 0) {
              const packageList = outdated.map(pkg => 
                `- ${pkg.name}: ${pkg.version} → ${pkg.latest_version}`
              ).join('\n');
              
              const issueBody = `## Outdated Dependencies Found

          The following packages have newer versions available:

          ${packageList}

          ### Recommendations:
          1. Review the changelog for each package
          2. Test updates in a development environment
          3. Update requirements.txt if tests pass

          This issue was automatically created by the dependency update workflow.`;

              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: `Dependency Updates Available - ${new Date().toISOString().split('T')[0]}`,
                body: issueBody,
                labels: ['dependencies', 'maintenance']
              });
            }
          } catch (error) {
            console.log('No outdated packages file found or error parsing:', error.message);
          }
